### ISSUE TITLE
Mac font issue

### ISSUE THREAD

**Issue by orionwills** [sggts04/dankcli#4] opened 2019-03-18 13:35 UTC
**Describe the bug**
Tried to use this and ran into the error below:
```
python -m dankcli flower.jpg "When I make a function"
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/dankcli/__main__.py", line 31, in <module>
    font = ImageFont.truetype('fonts/arial.ttf', size=getFontSize(img))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/PIL/ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/PIL/ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
OSError: cannot open resource
```

**To Reproduce**
Exact stuff you did:
I'm in the Downloads folder where the image is stored (flower.jpg)
2. Exact command typed
python -m dankcli flower.jpg "When I make a function"
python -m dankcli "~/Downloads/flower.jpg" "When I make a function"

**Expected behavior**
I expected to get an image with text on top 

**Setup in which bug happened:**
 - OS newest MacOS
 - Which command line/ terminal used(sometimes cmd on windows can be problematic)
python -m dankcli flower.jpg "When I make a function"

**Comment by sggts04** [comment] 2019-03-18 14:22
Clearly it can't open the font .ttf but why its happening is the question.

I can't really test on macOS so its gonna be a pickle solving this.

**Comment by orionwills** [comment] 2019-03-18 15:07
Well mac os fonts are .TFIL, .OTF, .TTC and for general use they are
located in /System/Library/Fonts

I'm happy to help test this with a little direction from you.  I have a
font in my fonts folder that is named ArialHB.TTC

How can I help troubleshoot this for you?  I'm also happy to help with the
python to help detect the OS of the user.

**Comment by dheiberg** [comment] 2019-03-18 16:03
So after some digging, it seems the issue isn't a Mac issue, but rather that it fails in such a way that it passes on Windows and not Mac. Looking at the docs for [ImageFont.truetype](https://pillow.readthedocs.io/en/3.1.x/reference/ImageFont.html#PIL.ImageFont.truetype), you can see that it has a fail condition specifically for Windows. 

The relevant [line](https://github.com/sggts04/dankcli/blob/master/dankcli/__main__.py#L31) in the code was using relative pathing, meaning that it was trying to look for a `fonts/arial.ttf` file where it was called from. You can check this by putting a `print(os.path.abspath(''))` in the code and it will print the directory you are calling the module from, not the directory the module is installed in. This coupled with the Windows specific fail safety means that it fails silently on Windows, but fails loudly on Mac. In order to fix this it should use absolute pathing based on the install location of the module, that *should* fix it.

I will setup a PR in a moment, please test it on your local installs and OS.

**Comment by sggts04** [comment] 2019-03-18 17:17
@orionwills @dhdavvie should be fixed in v0.5.3

Please do `pip install --upgrade dankcli` and check again so I could close this.

**Comment by orionwills** [comment] 2019-03-18 17:25
That fixed it on my end!  Thanks

**Comment by sggts04** [comment] 2019-03-18 17:27
Great, talked to @dhdavvie on discord, and its fixed on his side aswell.

Thanks a lot for the Issue :)

**Closed as completed by sggts04** 2019-03-18 17:27 UTC
Labels: bug
